friends_profile_homepage:
    path:     /hello/{name}
    defaults: { _controller: FriendsProfileBundle:Default:index }
friends_profile_twitterfeed:
    path:     /twitterfeed
    defaults: { _controller: FriendsProfileBundle:TwitterFeed:index }
friends_profile_messagegeneration:
    path:     /messagegeneration
    defaults: { _controller: FriendsProfileBundle:MessageGeneration:index }
friends_profile_requestResponse:
    path:     /requestResponse
    defaults: { _controller: FriendsProfileBundle:RequestResponse:index }
