friends_profile_homepage:
    path:     /hello/{name}
    defaults: { _controller: FriendsProfileBundle:Default:index, 'name' : "Thilanka" }
friends_profile_twitterfeed:
    path:     /twitterfeed
    defaults: { _controller: FriendsProfileBundle:TwitterFeed:index }
friends_profile_messagegeneration:
    path:     /messagegeneration
    defaults: { _controller: FriendsProfileBundle:MessageGeneration:index }
friends_profile_requestResponse:
    path:     /requestResponse
    defaults: { _controller: FriendsProfileBundle:RequestResponse:index }
friends_profile_routingTest:
    path:     /routingTest
    defaults: { _controller: FriendsProfileBundle:RoutingTest:routingTest }
    condition: "context.getMethod() in ['GET', 'POST']"
    methods:  [GET]
friends_profile_templateSample:
    path:     /templateSample
    defaults: { _controller: FriendsProfileBundle:TemplateSample:printList }
